services:
  hunter-seeker:
    build: .
    container_name: hunter-seeker-app
    ports:
      - "8080:8080"
    volumes:
      # Mount data directory to persist SQLite database
      - ./data:/root/data
    environment:
      - PORT=8080
      - DB_PATH=./data/jobs.db
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
